### ISSUE TITLE
Trying to load this script in an Azure function 

### ISSUE THREAD

**Issue by sm-palo** [TheScriptGuy/PrismaAccess-EgressIPs#9]
Hi TheScriptGuy,

I am trying to use this script in an Azure function, but getting an issue running I am getting the error below, as your script references the import command. 

Standard Error: Traceback (most recent call last): File "/home/site/wwwroot/format-egress-ip.py", line 13, in <module> import requests ModuleNotFoundError: No module named 'requests'.

On my Azure function requirements.txt file, I have listed requests as a package to be installed in the Azure function, but the error persists.  Any help would be useful. thanks.

**Comment by TheScriptGuy** [comment]
Hi @sm-palo !

Are you able to share your requirements.txt file? If you have some information of how you're provisioning your function, I can try and replicate the issue on my side.

**Comment by sm-palo** [comment]
# DO NOT include azure-functions-worker in this file
# The Python Worker is managed by Azure Functions platform
# Manually managing azure-functions-worker may cause unexpected issues

azure-functions
azure-storage-blob
requests

This is the content of the requirements document, I am trying to run a time trigger function to run your script. I am calling your script via the timer function, the function itself is a Python script, and the script will produce the output.csv file and upload to a storage blob.

**Comment by TheScriptGuy** [comment]
Thank you for sharing. I'm still doing some research.

What happens if you change the requests line to the following
requests>=2.28.0

Alternatively try running the `pip freeze > requirements.txt` on your working machine and then add that to your requirements.txt for the Azure function.

I found this link on Azure's website when it comes to [troubleshooting "ModuleNotFoundError"](https://learn.microsoft.com/en-us/azure/azure-functions/recover-python-functions?tabs=vscode%2Cbash&pivots=python-mode-decorators#troubleshoot-modulenotfounderror)

I also came across this post in [Reddit](https://www.reddit.com/r/AZURE/comments/yqwrrr/python_function_app_issue_modulenotfound_errors/) that talks about an issue with Python and Azure:
https://github.com/Azure/azure-functions-core-tools/issues/3042

**Comment by sm-palo** [comment]
Did you manage to create a function to upload the output.csv to a storage blob?

**Comment by sm-palo** [comment]
I have added a request statement in my timer trigger script which calls your format API script, and as you can see bellow it works.

Requests module works! Response: <!doctype html><html itemscope="" itemtype="http://schema.org/WebPage" lang="en-GB"><head><meta content="text/html; charset=UTF-8" http-equiv="Content-Type"><meta content="/images/branding/googleg/1x/googleg_standard_color_128dp.png" itemprop="image"><title>Google</title><script nonce="4RqEMBhvEZsmCjo9vmnFIg">(function(){var _g={kEI:'NnaqZf-sBcaLkdUPvN-

the bit of code i am using to call your code is and I think when using the cmd command it seems not to respect the requests module to be loaded.

   # Building the command
    cmd = ["python3", "format-egress-ip.py"]
    if all_egress_ips:
        cmd.append("--allEgressIPs")
        cmd.extend(["--apiKey", api_key])

**Comment by sm-palo** [comment]
Hi, did not fix the issue on the Python script but used your power shell script to do the job and works a treat.

**Comment by TheScriptGuy** [comment]
Glad to hear the Powershell script is working. If someone else has a similar problem, I'll cross the bridge at a future date. I appreciate your input here!
